// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mooddxbxvgnwpjoqrqmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vb2RkeGJ4dmdud3Bqb3FycW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjI0OTUsImV4cCI6MjA2OTI5ODQ5NX0._jCeW26omfJaObA16egXODgRUv-Qr8UZXROhhzZA8YA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});